### ISSUE TITLE
Generated code produces warnings for empty tables with Rust 1.77

### ISSUE THREAD

**Issue by stephanemagnenat** [planus-org/planus#230] opened 2024-03-21 17:13 UTC
For example:
```
warning: field `0` is never read
     --> app-core/src/game/planus_serialization.rs:13349:33
      |
13349 |         pub struct TouchRef<'a>(::planus::table_reader::Table<'a>);
      |                    --------     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |                    |
      |                    field in this struct
      |
      = note: `TouchRef` has a derived impl for the trait `Clone`, but this is intentionally ignored during dead code analysis
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
      |
13349 |         pub struct TouchRef<'a>(());
      |                                 ~~
```

Where `TouchRef` is the generated struct for an empty table:
```
table Touch {
}
```

**Comment by TethysSvensson** [comment] 2024-03-22 07:44
I am unable to replicate this after 5 minutes of trying.

Can you maybe expand a bit upon your setup? Do you perhaps have enabled non-default lints or something?

I *would* also ask you to tell me the version of the planus cli you used to generated this. I don't expect this to be the cause, but would be good to be sure to minimize any potential misunderstandings.

**However** it turns out that the planus cli does not have a version subcommand. I've filed #231 for this.

**Comment by stephanemagnenat** [comment] 2024-03-22 08:19
Given commit [ebcb3a0](https://github.com/planus-org/planus/commit/ebcb3a09971883a5d208097a5caf38ecb50eb8a7), should I assume that you have identified and solved the issue?

**Comment by TethysSvensson** [comment] 2024-03-22 08:21
Unfortunately not. I tried to write a test to see if I had actually fixed the issue and I was unable to trigger it even without that commit.

**Comment by TethysSvensson** [comment] 2024-03-22 08:23
If this is a deficiency in our testing, I want to get that deficiency resolved, so we actually catch these kinds of issues in the future.

If this turns out to be something specific to your setup, then I'll still want to fix it (probably using that commit), but not until we add testing to make sure it doesn't come back. Or at the very least, I want to run it on the entire repo manually to find related problems.

**Comment by stephanemagnenat** [comment] 2024-03-22 08:25
My planus-cli install command is: `cargo install planus-cli@0.4.0`.
I did not see any specific lint being used. I guess the next step is to make a minimal reproducible test case.

**Comment by stephanemagnenat** [comment] 2024-03-22 08:31
So I can confirm that if I take my planus-generated rs file and I copy it to a fresh repository, with Rust 1.77 I can reproduce the issue. Now I'll try to get a minimal file.

**Comment by stephanemagnenat** [comment] 2024-03-22 08:37
The test case is here: https://github.com/stephanemagnenat/planus-230

**Comment by TethysSvensson** [comment] 2024-03-22 08:43
Thanks!

I can confirm that this is fixed on main. I'll leave this issue open for now until we do a new release.

**Comment by TethysSvensson** [comment] 2024-11-08 12:34
We've done a new release with this fix.

**Closed by TethysSvensson** 2024-11-08 12:34 UTC
